/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"fmt"
)

import (
	"google.golang.org/grpc"
)

import (
	"github.com/apache/dubbo-go/config"
	"github.com/apache/dubbo-go/protocol"
	dgrpc "github.com/apache/dubbo-go/protocol/grpc"
	"github.com/apache/dubbo-go/protocol/invocation"
)

func init() {
	config.SetProviderService(NewGreeterProvider())
}

type GreeterProvider struct {
	*GreeterProviderBase
}

func NewGreeterProvider() *GreeterProvider {
	return &GreeterProvider{
		GreeterProviderBase: &GreeterProviderBase{
		},
	}
}

func (g *GreeterProvider) SayHello(ctx context.Context, req *HelloRequest) (reply *HelloReply, err error) {
	fmt.Printf("req: %v", req)
	return &HelloReply{Message: "this is message from reply"}, nil
}

func (g *GreeterProvider) Reference() string {
	return "GrpcGreeterImpl"
}

type GreeterProviderBase struct {
	proxyImpl protocol.Invoker
}

func (g *GreeterProviderBase) SetProxyImpl(impl protocol.Invoker) {
	g.proxyImpl = impl
}

func (g *GreeterProviderBase) GetProxyImpl() protocol.Invoker {
	return g.proxyImpl
}

func (g *GreeterProviderBase) ServiceDesc() *grpc.ServiceDesc {
	return &grpc.ServiceDesc{
		ServiceName: "helloworld.Greeter",
		HandlerType: (*GreeterServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "SayHello",
				Handler:    _DUBBO_Greeter_SayHello_Handler,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "helloworld.proto",
	}
}

// code generated by greeter.go
func _DUBBO_Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	//base := srv.(*GreeterProviderBase)
	base := srv.(dgrpc.DubboGrpcService)

	args := []interface{}{}
	args = append(args, in)
	invo := invocation.NewRPCInvocation("SayHello", args, nil)

	if interceptor == nil {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	return interceptor(ctx, in, info, handler)
}
